name: Documentation

on:
  push:
    branches:
    - master

env:
  CMAKE_VERSION: 3.22.2
  DOXYGEN_VERSION: 1.9.3
  DOXYGEN_LIBCLANG_VERSION: 9

jobs:
  build:
    name: ubuntu-20.04 - documentation
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout dynamic_bitset
      uses: actions/checkout@v2
      with:
        submodules: recursive
        path: dynamic_bitset

    - name: Setup CMake
      id: cmake
      uses: ./dynamic_bitset/.github/actions/setup_cmake
      with:
        cmake_version: ${{env.CMAKE_VERSION}}
        used_env: ${{matrix.config.os}}

    - name: Setup Doxygen
      id: doxygen
      uses: ./dynamic_bitset/.github/actions/setup_doxygen
      with:
        doxygen_version: ${{env.DOXYGEN_VERSION}}
        doxygen_libclang_version: ${{env.DOXYGEN_LIBCLANG_VERSION}}
        used_env: ubuntu-20.04

    - name: Configure
      shell: cmake -P {0}
      run: |
        file(TO_CMAKE_PATH [=[${{github.workspace}}]=] workspace)
        execute_process(
          COMMAND ${{steps.cmake.outputs.cmake_binary}}
            -S "${workspace}/dynamic_bitset"
            -B "${workspace}/dynamic_bitset/build"
            -D Doxygen_ROOT=${{steps.doxygen.outputs.doxygen_install}}
            -D CMAKE_POLICY_DEFAULT_CMP0074=NEW
          RESULT_VARIABLE result
        )
        if(NOT result EQUAL 0)
          message(FATAL_ERROR "Bad exit status")
        endif()

    - name: Build
      shell: cmake -P {0}
      run: |
        file(TO_CMAKE_PATH [=[${{github.workspace}}]=] workspace)
        execute_process(
          COMMAND ${{steps.cmake.outputs.cmake_binary}}
            --build "${workspace}/dynamic_bitset/build"
            --target dynamic_bitset_docs
          RESULT_VARIABLE result
        )
        if(NOT result EQUAL 0)
          message(FATAL_ERROR "Bad exit status")
        endif()

    - name: Deploy
      id: deploy
      run: |
        set -eu
        mkdir tmp-git
        cd tmp-git
        git init
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@bots.github.com"
        git remote add origin "https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"
        git fetch origin
        git checkout -t origin/gh-pages
        rm -rf ./*
        cp -r "${{github.workspace}}/dynamic_bitset/build/docs/html/." .
        git add -A .
        if git commit -m "Update"; then
            git push
            echo "documentation updated"
        else
            echo "no changes to commit"
        fi
