name: macOS

on:
  - push
  - pull_request

env:
  CMAKE_VERSION: 3.30.3

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config: [
          # {os: macos-12, xcode: 13.1},
          # {os: macos-12, xcode: 13.2.1},
          # {os: macos-12, xcode: 13.3.1},
          {os: macos-12, xcode: 13.4.1},
          # {os: macos-12, xcode: 14.0.1},
          # {os: macos-12, xcode: 14.1},
          {os: macos-12, xcode: 14.2},
          # {os: macos-13, xcode: 14.1},
          # {os: macos-13, xcode: 14.2},
          {os: macos-13, xcode: 14.3.1},
          # {os: macos-13, xcode: 15.0.1},
          # {os: macos-13, xcode: 15.1},
          {os: macos-13, xcode: 15.2},
          {os: macos-14, xcode: 14.3.1},
          # {os: macos-14, xcode: 15.0.1},
          # {os: macos-14, xcode: 15.1},
          # {os: macos-14, xcode: 15.2},
          # {os: macos-14, xcode: 15.3},
          {os: macos-14, xcode: 15.4},
        ]
        build_type: [Debug, Release, Sanitize]
    name: ${{matrix.config.os}} - Xcode ${{matrix.config.xcode}} - ${{matrix.build_type}}
    runs-on: ${{matrix.config.os}}
    env:
      CMAKE_GENERATOR: "Xcode"
      DEVELOPER_DIR: "/Applications/Xcode_${{matrix.config.xcode}}.app/Contents/Developer"

    steps:
    - name: Checkout dynamic_bitset
      uses: actions/checkout@v4
      with:
        submodules: recursive
        path: dynamic_bitset

    - name: Setup CMake
      id: cmake
      uses: ./dynamic_bitset/.github/actions/setup_cmake
      with:
        cmake_version: ${{env.CMAKE_VERSION}}
        used_env: ${{matrix.config.os}}

    - name: CMake version
      run: ${{steps.cmake.outputs.cmake_binary}} --version

    - name: CTest version
      run: ${{steps.cmake.outputs.ctest_binary}} --version

    - name: Configure
      run: >-
        ${{steps.cmake.outputs.cmake_binary}}
        -S "${{github.workspace}}/dynamic_bitset"
        -B "${{github.workspace}}/dynamic_bitset/build"
        -D CMAKE_CONFIGURATION_TYPES=${{matrix.build_type}}
        -D CMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      run: >-
        ${{steps.cmake.outputs.cmake_binary}}
        --build "${{github.workspace}}/dynamic_bitset/build"
        --config ${{matrix.build_type}}
        --parallel $(nproc)

    - name: Run tests
      run: >-
        ${{steps.cmake.outputs.ctest_binary}}
        --test-dir "${{github.workspace}}/dynamic_bitset/build"
        --output-on-failure
        --parallel $(nproc)
