name: Windows Visual Studio

on:
  - push
  - pull_request

env:
  CMAKE_VERSION: 3.30.3

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config: [
          {os: windows-2019, generator: "Visual Studio 16 2019", generator_short: VS2019, toolset: v142},
          {os: windows-2019, generator: "Visual Studio 16 2019", generator_short: VS2019, toolset: ClangCL},
          {os: windows-2022, generator: "Visual Studio 17 2022", generator_short: VS2022, toolset: v143},
          {os: windows-2022, generator: "Visual Studio 17 2022", generator_short: VS2022, toolset: ClangCL}
        ]
        architecture: [Win32, x64]
        build_type: [Debug, Release]
    name: ${{matrix.config.os}} - ${{matrix.config.generator_short}} - ${{matrix.config.toolset}} - ${{matrix.architecture}} - ${{matrix.build_type}}
    runs-on: ${{matrix.config.os}}
    env:
      CMAKE_GENERATOR: ${{matrix.config.generator}}
      CMAKE_GENERATOR_TOOLSET: ${{matrix.config.toolset}}
      CMAKE_GENERATOR_PLATFORM: ${{matrix.architecture}}

    steps:
    - name: Checkout dynamic_bitset
      uses: actions/checkout@v4
      with:
        submodules: recursive
        path: dynamic_bitset

    - name: Setup CMake
      id: cmake
      uses: ./dynamic_bitset/.github/actions/setup_cmake
      with:
        cmake_version: ${{env.CMAKE_VERSION}}
        used_env: ${{matrix.config.os}}

    - name: CMake version
      run: ${{steps.cmake.outputs.cmake_binary}} --version

    - name: CTest version
      run: ${{steps.cmake.outputs.ctest_binary}} --version

    - name: Configure
      run: >-
        ${{steps.cmake.outputs.cmake_binary}}
        -S "${{github.workspace}}/dynamic_bitset"
        -B "${{github.workspace}}/dynamic_bitset/build"
        -D CMAKE_CONFIGURATION_TYPES=${{matrix.build_type}}
        -D CMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      run: >-
        ${{steps.cmake.outputs.cmake_binary}}
        --build "${{github.workspace}}/dynamic_bitset/build"
        --config ${{matrix.build_type}}
        --parallel ${env:NUMBER_OF_PROCESSORS}

    - name: Run tests
      run: >-
        ${{steps.cmake.outputs.ctest_binary}}
        --test-dir "${{github.workspace}}/dynamic_bitset/build"
        --output-on-failure
        --parallel ${env:NUMBER_OF_PROCESSORS}
